// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await dotenv.load(fileName: ".get()");
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.get('WEB_API_KEY'),
    appId: '1:546588628816:web:7f2abfd4d356bc6d107e55',
    messagingSenderId: '546588628816',
    projectId: 'firstproject-dyyqpw',
    authDomain: 'firstproject-dyyqpw.firebaseapp.com',
    storageBucket: 'firstproject-dyyqpw.appspot.com',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.get('ANDROID_API_KEY'),
    appId: '1:546588628816:android:49e068753d9134df107e55',
    messagingSenderId: '546588628816',
    projectId: 'firstproject-dyyqpw',
    storageBucket: 'firstproject-dyyqpw.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.get('IOS_API_KEY'),
    appId: '1:546588628816:ios:1aaf2fe87a02dc8d107e55',
    messagingSenderId: '546588628816',
    projectId: 'firstproject-dyyqpw',
    storageBucket: 'firstproject-dyyqpw.appspot.com',
    iosClientId:
        '546588628816-dudu2r6oncpp51vpe6hnak4m6e7asuoa.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.get('Mac_API_KEY'),
    appId: '1:546588628816:ios:1aaf2fe87a02dc8d107e55',
    messagingSenderId: '546588628816',
    projectId: 'firstproject-dyyqpw',
    storageBucket: 'firstproject-dyyqpw.appspot.com',
    iosClientId:
        '546588628816-dudu2r6oncpp51vpe6hnak4m6e7asuoa.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.get('Win_API_KEY'),
    appId: '1:546588628816:web:d4dccbbf92a7195f107e55',
    messagingSenderId: '546588628816',
    projectId: 'firstproject-dyyqpw',
    authDomain: 'firstproject-dyyqpw.firebaseapp.com',
    storageBucket: 'firstproject-dyyqpw.appspot.com',
  );
}
